{{- if .Values.genai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codesourcerer.fullname" . }}-genai
  labels:
    {{- include "codesourcerer.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai
spec:
  type: {{ .Values.genai.service.type }}
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "codesourcerer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai
{{- end }}
